#!/bin/bash

father_dir=$(pwd | xargs -I {} dirname {})
build_dir="${father_dir}/1.CC_Build"
src_dir="${father_dir}/2.CC_src"
program_dir="${father_dir}/3.CC_Program"

case ${1} in 
    "--gengrate" | "-g")
        java -jar ${build_dir}/1.Need_file/1.Antlr_3.4/antlr-3.4-complete.jar ${src_dir}/ExprCppTree.g 
    ;;
    "--translater" | "-t")
        g++ -g ${src_dir}/*.c ${src_dir}/*.cpp  ${build_dir}/1.Need_file/*.o  -o ${program_dir}/MYCC 
        if [[ ${?} -eq 0  ]];
        then
            sudo cp ./MYCC /usr/bin/
        fi
    ;;
    *)
        java -jar ${build_dir}/1.Need_file/1.Antlr_3.4/antlr-3.4-complete.jar ${src_dir}/ExprCppTree.g 
        g++ -g ${src_dir}/*.c ${src_dir}/*.cpp  ${build_dir}/1.Need_file/*.o  -o ${program_dir}/MYCC 
        if [[ ${?} -eq 0  ]];
        then
            sudo cp ./MYCC /usr/bin/
        fi
    ;;
esac


