/** \file
 *  This C header file was generated by $ANTLR version 3.4
 *
 *     -  From the grammar source file : /home/sunowsir/GitHub/2.My_Project/10.Homemade_Programming_Language/5.CC_lib/ExprCppTree.g
 *     -                            On : 2019-04-03 15:21:43
 *     -                 for the lexer : ExprCppTreeLexerLexer
 *
 * Editing it, at least manually, is not wise.
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
 * The lexer 
ExprCppTreeLexer

has the callable functions (rules) shown below,
 * which will invoke the code for the associated rule in the source grammar
 * assuming that the input stream is pointing to a token/text stream that could begin
 * this rule.
 *
 * For instance if you call the first (topmost) rule in a parser grammar, you will
 * get the results of a full parse, but calling a rule half way through the grammar will
 * allow you to pass part of a full token stream to the parser, such as for syntax checking
 * in editors and so on.
 *
 * The parser entry points are called indirectly (by function pointer to function) via
 * a parser context typedef pExprCppTreeLexer, which is returned from a call to ExprCppTreeLexerNew().
 *
 * As this is a generated lexer, it is unlikely you will call it 'manually'. However
 * the methods are provided anyway.
 *
 * The methods in pExprCppTreeLexer are  as follows:
 *
 *  - 
 void
      pExprCppTreeLexer->T__40(pExprCppTreeLexer)
 *  - 
 void
      pExprCppTreeLexer->KW_MAIN(pExprCppTreeLexer)
 *  - 
 void
      pExprCppTreeLexer->KW_IF(pExprCppTreeLexer)
 *  - 
 void
      pExprCppTreeLexer->KW_ELIF(pExprCppTreeLexer)
 *  - 
 void
      pExprCppTreeLexer->KW_ELSE(pExprCppTreeLexer)
 *  - 
 void
      pExprCppTreeLexer->KW_FOR(pExprCppTreeLexer)
 *  - 
 void
      pExprCppTreeLexer->KW_WHILE(pExprCppTreeLexer)
 *  - 
 void
      pExprCppTreeLexer->KW_DO(pExprCppTreeLexer)
 *  - 
 void
      pExprCppTreeLexer->KW_DEF(pExprCppTreeLexer)
 *  - 
 void
      pExprCppTreeLexer->OPR_COMMA(pExprCppTreeLexer)
 *  - 
 void
      pExprCppTreeLexer->OPR_ASSIGN(pExprCppTreeLexer)
 *  - 
 void
      pExprCppTreeLexer->OPR_OR(pExprCppTreeLexer)
 *  - 
 void
      pExprCppTreeLexer->OPR_AND(pExprCppTreeLexer)
 *  - 
 void
      pExprCppTreeLexer->OPR_BIT_OR(pExprCppTreeLexer)
 *  - 
 void
      pExprCppTreeLexer->OPR_XOR(pExprCppTreeLexer)
 *  - 
 void
      pExprCppTreeLexer->OPR_BIT_AND(pExprCppTreeLexer)
 *  - 
 void
      pExprCppTreeLexer->OPR_EQ(pExprCppTreeLexer)
 *  - 
 void
      pExprCppTreeLexer->OPR_NE(pExprCppTreeLexer)
 *  - 
 void
      pExprCppTreeLexer->OPR_LT(pExprCppTreeLexer)
 *  - 
 void
      pExprCppTreeLexer->OPR_LE(pExprCppTreeLexer)
 *  - 
 void
      pExprCppTreeLexer->OPR_GT(pExprCppTreeLexer)
 *  - 
 void
      pExprCppTreeLexer->OPR_GE(pExprCppTreeLexer)
 *  - 
 void
      pExprCppTreeLexer->OPR_PLUS(pExprCppTreeLexer)
 *  - 
 void
      pExprCppTreeLexer->OPR_MINUS(pExprCppTreeLexer)
 *  - 
 void
      pExprCppTreeLexer->OPR_MULT(pExprCppTreeLexer)
 *  - 
 void
      pExprCppTreeLexer->OPR_DIVISOR(pExprCppTreeLexer)
 *  - 
 void
      pExprCppTreeLexer->OPR_PERCENT(pExprCppTreeLexer)
 *  - 
 void
      pExprCppTreeLexer->OPR_NOT(pExprCppTreeLexer)
 *  - 
 void
      pExprCppTreeLexer->PARENTHESES_LEFT(pExprCppTreeLexer)
 *  - 
 void
      pExprCppTreeLexer->PARENTHESES_RIGHT(pExprCppTreeLexer)
 *  - 
 void
      pExprCppTreeLexer->CURLY_BRACE_LEFT(pExprCppTreeLexer)
 *  - 
 void
      pExprCppTreeLexer->CURLY_BRACE_RIGHT(pExprCppTreeLexer)
 *  - 
 void
      pExprCppTreeLexer->ID(pExprCppTreeLexer)
 *  - 
 void
      pExprCppTreeLexer->INT(pExprCppTreeLexer)
 *  - 
 void
      pExprCppTreeLexer->ENDLINE(pExprCppTreeLexer)
 *  - 
 void
      pExprCppTreeLexer->WS(pExprCppTreeLexer)
 *  - 
 void
      pExprCppTreeLexer->Tokens(pExprCppTreeLexer)
 *
 * The return type for any particular rule is of course determined by the source
 * grammar file.
 */
// [The "BSD license"]
// Copyright (c) 2005-2009 Jim Idle, Temporal Wave LLC
// http://www.temporal-wave.com
// http://www.linkedin.com/in/jimidle
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

#ifndef	_ExprCppTreeLexer_H
#define _ExprCppTreeLexer_H
/* =============================================================================
 * Standard antlr3 C runtime definitions
 */
#include    <antlr3.h>

/* End of standard antlr 3 runtime definitions
 * =============================================================================
 */

#ifdef __cplusplus
extern "C" {
#endif

// Forward declare the context typedef so that we can use it before it is
// properly defined. Delegators and delegates (from import statements) are
// interdependent and their context structures contain pointers to each other
// C only allows such things to be declared if you pre-declare the typedef.
//
typedef struct ExprCppTreeLexer_Ctx_struct ExprCppTreeLexer, * pExprCppTreeLexer;



#ifdef	ANTLR3_WINDOWS
// Disable: Unreferenced parameter,							- Rules with parameters that are not used
//          constant conditional,							- ANTLR realizes that a prediction is always true (synpred usually)
//          initialized but unused variable					- tree rewrite variables declared but not needed
//          Unreferenced local variable						- lexer rule declares but does not always use _type
//          potentially unitialized variable used			- retval always returned from a rule
//			unreferenced local function has been removed	- susually getTokenNames or freeScope, they can go without warnigns
//
// These are only really displayed at warning level /W4 but that is the code ideal I am aiming at
// and the codegen must generate some of these warnings by necessity, apart from 4100, which is
// usually generated when a parser rule is given a parameter that it does not use. Mostly though
// this is a matter of orthogonality hence I disable that one.
//
#pragma warning( disable : 4100 )
#pragma warning( disable : 4101 )
#pragma warning( disable : 4127 )
#pragma warning( disable : 4189 )
#pragma warning( disable : 4505 )
#pragma warning( disable : 4701 )
#endif

/** Context tracking structure for 
ExprCppTreeLexer

 */
struct ExprCppTreeLexer_Ctx_struct
{
    /** Built in ANTLR3 context tracker contains all the generic elements
     *  required for context tracking.
     */
    pANTLR3_LEXER    pLexer;

     void
     (*mT__40)	(struct ExprCppTreeLexer_Ctx_struct * ctx);

     void
     (*mKW_MAIN)	(struct ExprCppTreeLexer_Ctx_struct * ctx);

     void
     (*mKW_IF)	(struct ExprCppTreeLexer_Ctx_struct * ctx);

     void
     (*mKW_ELIF)	(struct ExprCppTreeLexer_Ctx_struct * ctx);

     void
     (*mKW_ELSE)	(struct ExprCppTreeLexer_Ctx_struct * ctx);

     void
     (*mKW_FOR)	(struct ExprCppTreeLexer_Ctx_struct * ctx);

     void
     (*mKW_WHILE)	(struct ExprCppTreeLexer_Ctx_struct * ctx);

     void
     (*mKW_DO)	(struct ExprCppTreeLexer_Ctx_struct * ctx);

     void
     (*mKW_DEF)	(struct ExprCppTreeLexer_Ctx_struct * ctx);

     void
     (*mOPR_COMMA)	(struct ExprCppTreeLexer_Ctx_struct * ctx);

     void
     (*mOPR_ASSIGN)	(struct ExprCppTreeLexer_Ctx_struct * ctx);

     void
     (*mOPR_OR)	(struct ExprCppTreeLexer_Ctx_struct * ctx);

     void
     (*mOPR_AND)	(struct ExprCppTreeLexer_Ctx_struct * ctx);

     void
     (*mOPR_BIT_OR)	(struct ExprCppTreeLexer_Ctx_struct * ctx);

     void
     (*mOPR_XOR)	(struct ExprCppTreeLexer_Ctx_struct * ctx);

     void
     (*mOPR_BIT_AND)	(struct ExprCppTreeLexer_Ctx_struct * ctx);

     void
     (*mOPR_EQ)	(struct ExprCppTreeLexer_Ctx_struct * ctx);

     void
     (*mOPR_NE)	(struct ExprCppTreeLexer_Ctx_struct * ctx);

     void
     (*mOPR_LT)	(struct ExprCppTreeLexer_Ctx_struct * ctx);

     void
     (*mOPR_LE)	(struct ExprCppTreeLexer_Ctx_struct * ctx);

     void
     (*mOPR_GT)	(struct ExprCppTreeLexer_Ctx_struct * ctx);

     void
     (*mOPR_GE)	(struct ExprCppTreeLexer_Ctx_struct * ctx);

     void
     (*mOPR_PLUS)	(struct ExprCppTreeLexer_Ctx_struct * ctx);

     void
     (*mOPR_MINUS)	(struct ExprCppTreeLexer_Ctx_struct * ctx);

     void
     (*mOPR_MULT)	(struct ExprCppTreeLexer_Ctx_struct * ctx);

     void
     (*mOPR_DIVISOR)	(struct ExprCppTreeLexer_Ctx_struct * ctx);

     void
     (*mOPR_PERCENT)	(struct ExprCppTreeLexer_Ctx_struct * ctx);

     void
     (*mOPR_NOT)	(struct ExprCppTreeLexer_Ctx_struct * ctx);

     void
     (*mPARENTHESES_LEFT)	(struct ExprCppTreeLexer_Ctx_struct * ctx);

     void
     (*mPARENTHESES_RIGHT)	(struct ExprCppTreeLexer_Ctx_struct * ctx);

     void
     (*mCURLY_BRACE_LEFT)	(struct ExprCppTreeLexer_Ctx_struct * ctx);

     void
     (*mCURLY_BRACE_RIGHT)	(struct ExprCppTreeLexer_Ctx_struct * ctx);

     void
     (*mID)	(struct ExprCppTreeLexer_Ctx_struct * ctx);

     void
     (*mINT)	(struct ExprCppTreeLexer_Ctx_struct * ctx);

     void
     (*mENDLINE)	(struct ExprCppTreeLexer_Ctx_struct * ctx);

     void
     (*mWS)	(struct ExprCppTreeLexer_Ctx_struct * ctx);

     void
     (*mTokens)	(struct ExprCppTreeLexer_Ctx_struct * ctx);
    const char * (*getGrammarFileName)();
    void            (*reset)  (struct ExprCppTreeLexer_Ctx_struct * ctx);
    void	    (*free)   (struct ExprCppTreeLexer_Ctx_struct * ctx);
};

// Function protoypes for the constructor functions that external translation units
// such as delegators and delegates may wish to call.
//
ANTLR3_API pExprCppTreeLexer ExprCppTreeLexerNew         (
pANTLR3_INPUT_STREAM
 instream);
ANTLR3_API pExprCppTreeLexer ExprCppTreeLexerNewSSD      (
pANTLR3_INPUT_STREAM
 instream, pANTLR3_RECOGNIZER_SHARED_STATE state);

/** Symbolic definitions of all the tokens that the 
lexer
 will work with.
 * \{
 *
 * Antlr will define EOF, but we can't use that as it it is too common in
 * in C header files and that would be confusing. There is no way to filter this out at the moment
 * so we just undef it here for now. That isn't the value we get back from C recognizers
 * anyway. We are looking for ANTLR3_TOKEN_EOF.
 */
#ifdef	EOF
#undef	EOF
#endif
#ifdef	Tokens
#undef	Tokens
#endif
#define EOF      -1
#define T__40      40
#define CURLY_BRACE_LEFT      4
#define CURLY_BRACE_RIGHT      5
#define ENDLINE      6
#define ID      7
#define INT      8
#define KW_DEF      9
#define KW_DO      10
#define KW_ELIF      11
#define KW_ELSE      12
#define KW_FOR      13
#define KW_IF      14
#define KW_MAIN      15
#define KW_WHILE      16
#define OPR_AND      17
#define OPR_ASSIGN      18
#define OPR_BIT_AND      19
#define OPR_BIT_OR      20
#define OPR_COMMA      21
#define OPR_DIVISOR      22
#define OPR_EQ      23
#define OPR_GE      24
#define OPR_GT      25
#define OPR_LE      26
#define OPR_LT      27
#define OPR_MINUS      28
#define OPR_MULT      29
#define OPR_NE      30
#define OPR_NOT      31
#define OPR_OR      32
#define OPR_PERCENT      33
#define OPR_PLUS      34
#define OPR_XOR      35
#define PARENTHESES_LEFT      36
#define PARENTHESES_RIGHT      37
#define TOK_BLOCK      38
#define WS      39
#ifdef	EOF
#undef	EOF
#define	EOF	ANTLR3_TOKEN_EOF
#endif

#ifndef TOKENSOURCE
#define TOKENSOURCE(lxr) lxr->pLexer->rec->state->tokSource
#endif

/* End of token definitions for ExprCppTreeLexer
 * =============================================================================
 */
/** } */

#ifdef __cplusplus
}
#endif

#endif

/* END - Note:Keep extra line feed to satisfy UNIX systems */
