/** \file
 *  This C source file was generated by $ANTLR version 3.4
 *
 *     -  From the grammar source file : /home/sunowsir/GitHub/2.My_Project/10.Homemade_Programming_Language/5.CC_lib/ExprCppTree.g
 *     -                            On : 2019-04-03 15:21:43
 *     -                 for the lexer : ExprCppTreeLexerLexer
 *
 * Editing it, at least manually, is not wise.
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
*/
// [The "BSD license"]
// Copyright (c) 2005-2009 Jim Idle, Temporal Wave LLC
// http://www.temporal-wave.com
// http://www.linkedin.com/in/jimidle
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

/* -----------------------------------------
 * Include the ANTLR3 generated header file.
 */
#include    "ExprCppTreeLexer.h"
/* ----------------------------------------- */


/** String literals used by ExprCppTreeLexer that we must do things like MATCHS() with.
 *  C will normally just lay down 8 bit characters, and you can use L"xxx" to
 *  get wchar_t, but wchar_t is 16 bits on Windows, which is not UTF32 and so
 *  we perform this little trick of defining the literals as arrays of UINT32
 *  and passing in the address of these.
 */
static ANTLR3_UCHAR	lit_1[]  = { 0x6D, 0x61, 0x69, 0x6E,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_2[]  = { 0x69, 0x66,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_3[]  = { 0x65, 0x6C, 0x69, 0x66,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_4[]  = { 0x65, 0x6C, 0x73, 0x65,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_5[]  = { 0x66, 0x6F, 0x72,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_6[]  = { 0x77, 0x68, 0x69, 0x6C, 0x65,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_7[]  = { 0x64, 0x6F,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_8[]  = { 0x64, 0x65, 0x66,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_9[]  = { 0x7C, 0x7C,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_10[]  = { 0x26, 0x26,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_11[]  = { 0x3D, 0x3D,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_12[]  = { 0x21, 0x3D,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_13[]  = { 0x3C, 0x3D,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_14[]  = { 0x3E, 0x3D,  ANTLR3_STRING_TERMINATOR};





/* MACROS that hide the C interface implementations from the
 * generated code, which makes it a little more understandable to the human eye.
 * I am very much against using C pre-processor macros for function calls and bits
 * of code as you cannot see what is happening when single stepping in debuggers
 * and so on. The exception (in my book at least) is for generated code, where you are
 * not maintaining it, but may wish to read and understand it. If you single step it, you know that input()
 * hides some indirect calls, but is always referring to the input stream. This is
 * probably more readable than ctx->input->istream->input(snarfle0->blarg) and allows me to rejig
 * the runtime interfaces without changing the generated code too often, without
 * confusing the reader of the generated output, who may not wish to know the gory
 * details of the interface inheritance.
 */

#define		CTX	ctx

/* Aids in accessing scopes for grammar programmers
 */
#undef	SCOPE_TYPE
#undef	SCOPE_STACK
#undef	SCOPE_TOP
#define	SCOPE_TYPE(scope)   pExprCppTreeLexer_##scope##_SCOPE
#define SCOPE_STACK(scope)  pExprCppTreeLexer_##scope##Stack
#define	SCOPE_TOP(scope)    ctx->pExprCppTreeLexer_##scope##Top
#define	SCOPE_SIZE(scope)		ctx->pExprCppTreeLexer_##scope##Stack_limit
#define SCOPE_INSTANCE(scope, i)	(ctx->SCOPE_STACK(scope)->get(ctx->SCOPE_STACK(scope),i))


/* Macros for accessing things in a lexer
 */
#undef	    LEXER
#undef	    RECOGNIZER
#undef	    RULEMEMO
#undef	    GETCHARINDEX
#undef	    GETLINE
#undef	    GETCHARPOSITIONINLINE
#undef	    EMIT
#undef	    EMITNEW
#undef	    MATCHC
#undef	    MATCHS
#undef	    MATCHRANGE
#undef	    LTOKEN
#undef	    HASFAILED
#undef	    FAILEDFLAG
#undef	    INPUT
#undef	    STRSTREAM
#undef	    LA
#undef	    HASEXCEPTION
#undef	    EXCEPTION
#undef	    CONSTRUCTEX
#undef	    CONSUME
#undef	    LRECOVER
#undef	    MARK
#undef	    REWIND
#undef	    REWINDLAST
#undef	    BACKTRACKING
#undef		MATCHANY
#undef		MEMOIZE
#undef		HAVEPARSEDRULE
#undef		GETTEXT
#undef		INDEX
#undef		SEEK
#undef		PUSHSTREAM
#undef		POPSTREAM
#undef		SETTEXT
#undef		SETTEXT8

#define	    LEXER					ctx->pLexer
#define	    RECOGNIZER			    LEXER->rec
#define		LEXSTATE				RECOGNIZER->state
#define		TOKSOURCE				LEXSTATE->tokSource
#define	    GETCHARINDEX()			LEXER->getCharIndex(LEXER)
#define	    GETLINE()				LEXER->getLine(LEXER)
#define	    GETTEXT()				LEXER->getText(LEXER)
#define	    GETCHARPOSITIONINLINE() LEXER->getCharPositionInLine(LEXER)
#define	    EMIT()					LEXSTATE->type = _type; LEXER->emit(LEXER)
#define	    EMITNEW(t)				LEXER->emitNew(LEXER, t)
#define	    MATCHC(c)				LEXER->matchc(LEXER, c)
#define	    MATCHS(s)				LEXER->matchs(LEXER, s)
#define	    MATCHRANGE(c1,c2)	    LEXER->matchRange(LEXER, c1, c2)
#define	    MATCHANY()				LEXER->matchAny(LEXER)
#define	    LTOKEN  				LEXSTATE->token
#define	    HASFAILED()				(LEXSTATE->failed == ANTLR3_TRUE)
#define	    BACKTRACKING			LEXSTATE->backtracking
#define	    FAILEDFLAG				LEXSTATE->failed
#define	    INPUT					LEXER->input
#define	    STRSTREAM				INPUT
#define		ISTREAM					INPUT->istream
#define		INDEX()					ISTREAM->index(ISTREAM)
#define		SEEK(n)					ISTREAM->seek(ISTREAM, n)
#define	    EOF_TOKEN				&(LEXSTATE->tokSource->eofToken)
#define	    HASEXCEPTION()			(LEXSTATE->error == ANTLR3_TRUE)
#define	    EXCEPTION				LEXSTATE->exception
#define	    CONSTRUCTEX()			RECOGNIZER->exConstruct(RECOGNIZER)
#define	    LRECOVER()				LEXER->recover(LEXER)
#define	    MARK()					ISTREAM->mark(ISTREAM)
#define	    REWIND(m)				ISTREAM->rewind(ISTREAM, m)
#define	    REWINDLAST()			ISTREAM->rewindLast(ISTREAM)
#define		MEMOIZE(ri,si)			RECOGNIZER->memoize(RECOGNIZER, ri, si)
#define		HAVEPARSEDRULE(r)		RECOGNIZER->alreadyParsedRule(RECOGNIZER, r)
#define		PUSHSTREAM(str)			LEXER->pushCharStream(LEXER, str)
#define		POPSTREAM()				LEXER->popCharStream(LEXER)
#define		SETTEXT(str)			LEXSTATE->text = str
#define		SKIP()					LEXSTATE->token = &(TOKSOURCE->skipToken)
#define		USER1					LEXSTATE->user1
#define		USER2					LEXSTATE->user2
#define		USER3					LEXSTATE->user3
#define		CUSTOM					LEXSTATE->custom
#define		RULEMEMO				LEXSTATE->ruleMemo
#define		DBG						RECOGNIZER->debugger

/* If we have been told we can rely on the standard 8 bit or UTF16 input
 * stream, then we can define our macros to use the direct pointers
 * in the input object, which is much faster than indirect calls. This
 * is really only significant to lexers with a lot of fragment rules (which
 * do not place LA(1) in a temporary at the moment) and even then
 * only if there is a lot of input (order of say 1M or so).
 */
#if	defined(ANTLR3_INLINE_INPUT_8BIT) || defined(ANTLR3_INLINE_INPUT_UTF16)

# ifdef	ANTLR3_INLINE_INPUT_8BIT

/* 8 bit character set */

#  define	    NEXTCHAR	((pANTLR3_UINT8)(INPUT->nextChar))
#  define	    DATAP	((pANTLR3_UINT8)(INPUT->data))

# else

#  define	    NEXTCHAR	((pANTLR3_UINT16)(INPUT->nextChar))
#  define	    DATAP	((pANTLR3_UINT16)(INPUT->data))

# endif

# define	    LA(n) ((NEXTCHAR + n) > (DATAP + INPUT->sizeBuf) ? ANTLR3_CHARSTREAM_EOF : (ANTLR3_UCHAR)(*(NEXTCHAR + n - 1)))
# define            CONSUME()                                           \
{                                                                       \
    if        (NEXTCHAR < (DATAP + INPUT->sizeBuf))                     \
    {                                                                   \
        INPUT->charPositionInLine++;                                    \
        if  ((ANTLR3_UCHAR)(*NEXTCHAR) == INPUT->newlineChar)           \
        {                                                               \
            INPUT->line++;                                              \
            INPUT->charPositionInLine        = 0;                       \
            INPUT->currentLine                = (void *)(NEXTCHAR + 1); \
        }                                                               \
        INPUT->nextChar = (void *)(NEXTCHAR + 1);                       \
    }                                                                   \
}

#else

// Pick up the input character by calling the input stream implementation.
//
#define	    CONSUME()   INPUT->istream->consume(INPUT->istream)
#define	    LA(n)       INPUT->istream->_LA(INPUT->istream, n)

#endif

#define		TOKTEXT(tok, txt)				tok, (pANTLR3_UINT8)txt

/* The 4 tokens defined below may well clash with your own #defines or token types. If so
 * then for the present you must use different names for your defines as these are hard coded
 * in the code generator. It would be better not to use such names internally, and maybe
 * we can change this in a forthcoming release. I deliberately do not #undef these
 * here as this will at least give you a redefined error somewhere if they clash.
 */
#define	    UP	    ANTLR3_TOKEN_UP
#define	    DOWN    ANTLR3_TOKEN_DOWN
#define	    EOR	    ANTLR3_TOKEN_EOR
#define	    INVALID ANTLR3_TOKEN_INVALID


/* =============================================================================
 * Functions to create and destroy scopes. First come the rule scopes, followed
 * by the global declared scopes.
 */



/* ============================================================================= */

/* =============================================================================
 * Start of recognizer
 */

/* Forward declare the locally static matching functions we have generated and any predicate functions.
 */
static ANTLR3_INLINE 
 void
	mT__40    (pExprCppTreeLexer ctx);
static ANTLR3_INLINE 
 void
	mKW_MAIN    (pExprCppTreeLexer ctx);
static ANTLR3_INLINE 
 void
	mKW_IF    (pExprCppTreeLexer ctx);
static ANTLR3_INLINE 
 void
	mKW_ELIF    (pExprCppTreeLexer ctx);
static ANTLR3_INLINE 
 void
	mKW_ELSE    (pExprCppTreeLexer ctx);
static ANTLR3_INLINE 
 void
	mKW_FOR    (pExprCppTreeLexer ctx);
static ANTLR3_INLINE 
 void
	mKW_WHILE    (pExprCppTreeLexer ctx);
static ANTLR3_INLINE 
 void
	mKW_DO    (pExprCppTreeLexer ctx);
static ANTLR3_INLINE 
 void
	mKW_DEF    (pExprCppTreeLexer ctx);
static ANTLR3_INLINE 
 void
	mOPR_COMMA    (pExprCppTreeLexer ctx);
static ANTLR3_INLINE 
 void
	mOPR_ASSIGN    (pExprCppTreeLexer ctx);
static ANTLR3_INLINE 
 void
	mOPR_OR    (pExprCppTreeLexer ctx);
static ANTLR3_INLINE 
 void
	mOPR_AND    (pExprCppTreeLexer ctx);
static ANTLR3_INLINE 
 void
	mOPR_BIT_OR    (pExprCppTreeLexer ctx);
static ANTLR3_INLINE 
 void
	mOPR_XOR    (pExprCppTreeLexer ctx);
static ANTLR3_INLINE 
 void
	mOPR_BIT_AND    (pExprCppTreeLexer ctx);
static ANTLR3_INLINE 
 void
	mOPR_EQ    (pExprCppTreeLexer ctx);
static ANTLR3_INLINE 
 void
	mOPR_NE    (pExprCppTreeLexer ctx);
static ANTLR3_INLINE 
 void
	mOPR_LT    (pExprCppTreeLexer ctx);
static ANTLR3_INLINE 
 void
	mOPR_LE    (pExprCppTreeLexer ctx);
static ANTLR3_INLINE 
 void
	mOPR_GT    (pExprCppTreeLexer ctx);
static ANTLR3_INLINE 
 void
	mOPR_GE    (pExprCppTreeLexer ctx);
static ANTLR3_INLINE 
 void
	mOPR_PLUS    (pExprCppTreeLexer ctx);
static ANTLR3_INLINE 
 void
	mOPR_MINUS    (pExprCppTreeLexer ctx);
static ANTLR3_INLINE 
 void
	mOPR_MULT    (pExprCppTreeLexer ctx);
static ANTLR3_INLINE 
 void
	mOPR_DIVISOR    (pExprCppTreeLexer ctx);
static ANTLR3_INLINE 
 void
	mOPR_PERCENT    (pExprCppTreeLexer ctx);
static ANTLR3_INLINE 
 void
	mOPR_NOT    (pExprCppTreeLexer ctx);
static ANTLR3_INLINE 
 void
	mPARENTHESES_LEFT    (pExprCppTreeLexer ctx);
static ANTLR3_INLINE 
 void
	mPARENTHESES_RIGHT    (pExprCppTreeLexer ctx);
static ANTLR3_INLINE 
 void
	mCURLY_BRACE_LEFT    (pExprCppTreeLexer ctx);
static ANTLR3_INLINE 
 void
	mCURLY_BRACE_RIGHT    (pExprCppTreeLexer ctx);
static ANTLR3_INLINE 
 void
	mID    (pExprCppTreeLexer ctx);
static ANTLR3_INLINE 
 void
	mINT    (pExprCppTreeLexer ctx);
static ANTLR3_INLINE 
 void
	mENDLINE    (pExprCppTreeLexer ctx);
static ANTLR3_INLINE 
 void
	mWS    (pExprCppTreeLexer ctx);
static ANTLR3_INLINE 
 void
	mTokens    (pExprCppTreeLexer ctx);
static void	ExprCppTreeLexerFree(pExprCppTreeLexer ctx);

/* =========================================================================
 * Lexer matching rules end.
 * =========================================================================
 */



static void
ExprCppTreeLexerFree  (pExprCppTreeLexer ctx)
{
    LEXER->free(LEXER);

    ANTLR3_FREE(ctx);
}

static void
ExprCppTreeLexerReset (pExprCppTreeLexer ctx)
{
    RECOGNIZER->reset(RECOGNIZER);
}

/** \brief Name of the grammar file that generated this code
 */
static const char fileName[] = "/home/sunowsir/GitHub/2.My_Project/10.Homemade_Programming_Language/5.CC_lib/ExprCppTree.g";

/** \brief Return the name of the grammar file that generated this code.
 */
static const char * getGrammarFileName()
{
	return fileName;
}

/** \brief Create a new lexer called ExprCppTreeLexer
 *
 * \param[in]    instream Pointer to an initialized input stream
 * \return
 *     - Success pExprCppTreeLexer initialized for the lex start
 *     - Fail NULL
 */
ANTLR3_API pExprCppTreeLexer ExprCppTreeLexerNew
(
pANTLR3_INPUT_STREAM
 instream)
{
	// See if we can create a new lexer with the standard constructor
	//
	return ExprCppTreeLexerNewSSD(instream, NULL);
}

/** \brief Create a new lexer called ExprCppTreeLexer
 *
 * \param[in]    instream Pointer to an initialized input stream
 * \param[state] state Previously created shared recognizer stat
 * \return
 *     - Success pExprCppTreeLexer initialized for the lex start
 *     - Fail NULL
 */
ANTLR3_API pExprCppTreeLexer ExprCppTreeLexerNewSSD
(pANTLR3_INPUT_STREAM instream, pANTLR3_RECOGNIZER_SHARED_STATE state)
{
    pExprCppTreeLexer ctx; // Context structure we will build and return

    ctx = (pExprCppTreeLexer) ANTLR3_CALLOC(1, sizeof(ExprCppTreeLexer));

    if  (ctx == NULL)
    {
        // Failed to allocate memory for lexer context
        return  NULL;
    }

    /* -------------------------------------------------------------------
     * Memory for basic structure is allocated, now to fill in
     * in base ANTLR3 structures. We initialize the function pointers
     * for the standard ANTLR3 lexer function set, but upon return
     * from here, the programmer may set the pointers to provide custom
     * implementations of each function.
     *
     * We don't use the macros defined in ExprCppTreeLexer.h here so you can get a sense
     * of what goes where.
     */

    /* Create a base lexer, using the supplied input stream
     */
    ctx->pLexer	= antlr3LexerNewStream(ANTLR3_SIZE_HINT, instream, state);

    /* Check that we allocated the memory correctly
     */
    if	(ctx->pLexer == NULL)
    {
		ANTLR3_FREE(ctx);
		return  NULL;
    }
    /* Install the implementation of our ExprCppTreeLexer interface
     */
    ctx->mT__40	= mT__40;
    ctx->mKW_MAIN	= mKW_MAIN;
    ctx->mKW_IF	= mKW_IF;
    ctx->mKW_ELIF	= mKW_ELIF;
    ctx->mKW_ELSE	= mKW_ELSE;
    ctx->mKW_FOR	= mKW_FOR;
    ctx->mKW_WHILE	= mKW_WHILE;
    ctx->mKW_DO	= mKW_DO;
    ctx->mKW_DEF	= mKW_DEF;
    ctx->mOPR_COMMA	= mOPR_COMMA;
    ctx->mOPR_ASSIGN	= mOPR_ASSIGN;
    ctx->mOPR_OR	= mOPR_OR;
    ctx->mOPR_AND	= mOPR_AND;
    ctx->mOPR_BIT_OR	= mOPR_BIT_OR;
    ctx->mOPR_XOR	= mOPR_XOR;
    ctx->mOPR_BIT_AND	= mOPR_BIT_AND;
    ctx->mOPR_EQ	= mOPR_EQ;
    ctx->mOPR_NE	= mOPR_NE;
    ctx->mOPR_LT	= mOPR_LT;
    ctx->mOPR_LE	= mOPR_LE;
    ctx->mOPR_GT	= mOPR_GT;
    ctx->mOPR_GE	= mOPR_GE;
    ctx->mOPR_PLUS	= mOPR_PLUS;
    ctx->mOPR_MINUS	= mOPR_MINUS;
    ctx->mOPR_MULT	= mOPR_MULT;
    ctx->mOPR_DIVISOR	= mOPR_DIVISOR;
    ctx->mOPR_PERCENT	= mOPR_PERCENT;
    ctx->mOPR_NOT	= mOPR_NOT;
    ctx->mPARENTHESES_LEFT	= mPARENTHESES_LEFT;
    ctx->mPARENTHESES_RIGHT	= mPARENTHESES_RIGHT;
    ctx->mCURLY_BRACE_LEFT	= mCURLY_BRACE_LEFT;
    ctx->mCURLY_BRACE_RIGHT	= mCURLY_BRACE_RIGHT;
    ctx->mID	= mID;
    ctx->mINT	= mINT;
    ctx->mENDLINE	= mENDLINE;
    ctx->mWS	= mWS;
    ctx->mTokens	= mTokens;

    /** When the nextToken() call is made to this lexer's pANTLR3_TOKEN_SOURCE
     *  it will call mTokens() in this generated code, and will pass it the ctx
     * pointer of this lexer, not the context of the base lexer, so store that now.
     */
    ctx->pLexer->ctx	    = ctx;

    /**Install the token matching function
     */
    ctx->pLexer->mTokens = (void (*) (void *))(mTokens);

    ctx->getGrammarFileName	= getGrammarFileName;
    ctx->free		= ExprCppTreeLexerFree;
    ctx->reset          = ExprCppTreeLexerReset;


    /* Return the newly built lexer to the caller
     */
    return  ctx;
}
/* =========================================================================
 * Functions to match the lexer grammar defined tokens from the input stream
 */

//   Comes from: 7:7: ( ';' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__40
 *
 * Looks to match the characters the constitute the token T__40
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__40(pExprCppTreeLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__40;


    // /home/sunowsir/GitHub/2.My_Project/10.Homemade_Programming_Language/5.CC_lib/ExprCppTree.g:7:7: ( ';' )
    // /home/sunowsir/GitHub/2.My_Project/10.Homemade_Programming_Language/5.CC_lib/ExprCppTree.g:7:9: ';'
    {
        MATCHC(';');
        if  (HASEXCEPTION())
        {
            goto ruleT__40Ex;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__40Ex; /* Prevent compiler warnings */
    ruleT__40Ex: ;

}
// $ANTLR end T__40

//   Comes from: 143:8: ( 'main' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start KW_MAIN
 *
 * Looks to match the characters the constitute the token KW_MAIN
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mKW_MAIN(pExprCppTreeLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = KW_MAIN;


    // /home/sunowsir/GitHub/2.My_Project/10.Homemade_Programming_Language/5.CC_lib/ExprCppTree.g:143:8: ( 'main' )
    // /home/sunowsir/GitHub/2.My_Project/10.Homemade_Programming_Language/5.CC_lib/ExprCppTree.g:143:13: 'main'
    {
        MATCHS(lit_1);
        if  (HASEXCEPTION())
        {
            goto ruleKW_MAINEx;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleKW_MAINEx; /* Prevent compiler warnings */
    ruleKW_MAINEx: ;

}
// $ANTLR end KW_MAIN

//   Comes from: 144:6: ( 'if' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start KW_IF
 *
 * Looks to match the characters the constitute the token KW_IF
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mKW_IF(pExprCppTreeLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = KW_IF;


    // /home/sunowsir/GitHub/2.My_Project/10.Homemade_Programming_Language/5.CC_lib/ExprCppTree.g:144:6: ( 'if' )
    // /home/sunowsir/GitHub/2.My_Project/10.Homemade_Programming_Language/5.CC_lib/ExprCppTree.g:144:13: 'if'
    {
        MATCHS(lit_2);
        if  (HASEXCEPTION())
        {
            goto ruleKW_IFEx;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleKW_IFEx; /* Prevent compiler warnings */
    ruleKW_IFEx: ;

}
// $ANTLR end KW_IF

//   Comes from: 145:8: ( 'elif' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start KW_ELIF
 *
 * Looks to match the characters the constitute the token KW_ELIF
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mKW_ELIF(pExprCppTreeLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = KW_ELIF;


    // /home/sunowsir/GitHub/2.My_Project/10.Homemade_Programming_Language/5.CC_lib/ExprCppTree.g:145:8: ( 'elif' )
    // /home/sunowsir/GitHub/2.My_Project/10.Homemade_Programming_Language/5.CC_lib/ExprCppTree.g:145:13: 'elif'
    {
        MATCHS(lit_3);
        if  (HASEXCEPTION())
        {
            goto ruleKW_ELIFEx;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleKW_ELIFEx; /* Prevent compiler warnings */
    ruleKW_ELIFEx: ;

}
// $ANTLR end KW_ELIF

//   Comes from: 146:8: ( 'else' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start KW_ELSE
 *
 * Looks to match the characters the constitute the token KW_ELSE
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mKW_ELSE(pExprCppTreeLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = KW_ELSE;


    // /home/sunowsir/GitHub/2.My_Project/10.Homemade_Programming_Language/5.CC_lib/ExprCppTree.g:146:8: ( 'else' )
    // /home/sunowsir/GitHub/2.My_Project/10.Homemade_Programming_Language/5.CC_lib/ExprCppTree.g:146:13: 'else'
    {
        MATCHS(lit_4);
        if  (HASEXCEPTION())
        {
            goto ruleKW_ELSEEx;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleKW_ELSEEx; /* Prevent compiler warnings */
    ruleKW_ELSEEx: ;

}
// $ANTLR end KW_ELSE

//   Comes from: 147:7: ( 'for' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start KW_FOR
 *
 * Looks to match the characters the constitute the token KW_FOR
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mKW_FOR(pExprCppTreeLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = KW_FOR;


    // /home/sunowsir/GitHub/2.My_Project/10.Homemade_Programming_Language/5.CC_lib/ExprCppTree.g:147:7: ( 'for' )
    // /home/sunowsir/GitHub/2.My_Project/10.Homemade_Programming_Language/5.CC_lib/ExprCppTree.g:147:13: 'for'
    {
        MATCHS(lit_5);
        if  (HASEXCEPTION())
        {
            goto ruleKW_FOREx;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleKW_FOREx; /* Prevent compiler warnings */
    ruleKW_FOREx: ;

}
// $ANTLR end KW_FOR

//   Comes from: 148:9: ( 'while' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start KW_WHILE
 *
 * Looks to match the characters the constitute the token KW_WHILE
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mKW_WHILE(pExprCppTreeLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = KW_WHILE;


    // /home/sunowsir/GitHub/2.My_Project/10.Homemade_Programming_Language/5.CC_lib/ExprCppTree.g:148:9: ( 'while' )
    // /home/sunowsir/GitHub/2.My_Project/10.Homemade_Programming_Language/5.CC_lib/ExprCppTree.g:148:13: 'while'
    {
        MATCHS(lit_6);
        if  (HASEXCEPTION())
        {
            goto ruleKW_WHILEEx;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleKW_WHILEEx; /* Prevent compiler warnings */
    ruleKW_WHILEEx: ;

}
// $ANTLR end KW_WHILE

//   Comes from: 149:6: ( 'do' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start KW_DO
 *
 * Looks to match the characters the constitute the token KW_DO
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mKW_DO(pExprCppTreeLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = KW_DO;


    // /home/sunowsir/GitHub/2.My_Project/10.Homemade_Programming_Language/5.CC_lib/ExprCppTree.g:149:6: ( 'do' )
    // /home/sunowsir/GitHub/2.My_Project/10.Homemade_Programming_Language/5.CC_lib/ExprCppTree.g:149:13: 'do'
    {
        MATCHS(lit_7);
        if  (HASEXCEPTION())
        {
            goto ruleKW_DOEx;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleKW_DOEx; /* Prevent compiler warnings */
    ruleKW_DOEx: ;

}
// $ANTLR end KW_DO

//   Comes from: 150:7: ( 'def' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start KW_DEF
 *
 * Looks to match the characters the constitute the token KW_DEF
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mKW_DEF(pExprCppTreeLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = KW_DEF;


    // /home/sunowsir/GitHub/2.My_Project/10.Homemade_Programming_Language/5.CC_lib/ExprCppTree.g:150:7: ( 'def' )
    // /home/sunowsir/GitHub/2.My_Project/10.Homemade_Programming_Language/5.CC_lib/ExprCppTree.g:150:13: 'def'
    {
        MATCHS(lit_8);
        if  (HASEXCEPTION())
        {
            goto ruleKW_DEFEx;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleKW_DEFEx; /* Prevent compiler warnings */
    ruleKW_DEFEx: ;

}
// $ANTLR end KW_DEF

//   Comes from: 154:10: ( ',' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start OPR_COMMA
 *
 * Looks to match the characters the constitute the token OPR_COMMA
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mOPR_COMMA(pExprCppTreeLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = OPR_COMMA;


    // /home/sunowsir/GitHub/2.My_Project/10.Homemade_Programming_Language/5.CC_lib/ExprCppTree.g:154:10: ( ',' )
    // /home/sunowsir/GitHub/2.My_Project/10.Homemade_Programming_Language/5.CC_lib/ExprCppTree.g:154:12: ','
    {
        MATCHC(',');
        if  (HASEXCEPTION())
        {
            goto ruleOPR_COMMAEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleOPR_COMMAEx; /* Prevent compiler warnings */
    ruleOPR_COMMAEx: ;

}
// $ANTLR end OPR_COMMA

//   Comes from: 155:11: ( '=' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start OPR_ASSIGN
 *
 * Looks to match the characters the constitute the token OPR_ASSIGN
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mOPR_ASSIGN(pExprCppTreeLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = OPR_ASSIGN;


    // /home/sunowsir/GitHub/2.My_Project/10.Homemade_Programming_Language/5.CC_lib/ExprCppTree.g:155:11: ( '=' )
    // /home/sunowsir/GitHub/2.My_Project/10.Homemade_Programming_Language/5.CC_lib/ExprCppTree.g:155:13: '='
    {
        MATCHC('=');
        if  (HASEXCEPTION())
        {
            goto ruleOPR_ASSIGNEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleOPR_ASSIGNEx; /* Prevent compiler warnings */
    ruleOPR_ASSIGNEx: ;

}
// $ANTLR end OPR_ASSIGN

//   Comes from: 156:7: ( '||' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start OPR_OR
 *
 * Looks to match the characters the constitute the token OPR_OR
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mOPR_OR(pExprCppTreeLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = OPR_OR;


    // /home/sunowsir/GitHub/2.My_Project/10.Homemade_Programming_Language/5.CC_lib/ExprCppTree.g:156:7: ( '||' )
    // /home/sunowsir/GitHub/2.My_Project/10.Homemade_Programming_Language/5.CC_lib/ExprCppTree.g:156:9: '||'
    {
        MATCHS(lit_9);
        if  (HASEXCEPTION())
        {
            goto ruleOPR_OREx;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleOPR_OREx; /* Prevent compiler warnings */
    ruleOPR_OREx: ;

}
// $ANTLR end OPR_OR

//   Comes from: 157:8: ( '&&' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start OPR_AND
 *
 * Looks to match the characters the constitute the token OPR_AND
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mOPR_AND(pExprCppTreeLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = OPR_AND;


    // /home/sunowsir/GitHub/2.My_Project/10.Homemade_Programming_Language/5.CC_lib/ExprCppTree.g:157:8: ( '&&' )
    // /home/sunowsir/GitHub/2.My_Project/10.Homemade_Programming_Language/5.CC_lib/ExprCppTree.g:157:10: '&&'
    {
        MATCHS(lit_10);
        if  (HASEXCEPTION())
        {
            goto ruleOPR_ANDEx;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleOPR_ANDEx; /* Prevent compiler warnings */
    ruleOPR_ANDEx: ;

}
// $ANTLR end OPR_AND

//   Comes from: 158:11: ( '|' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start OPR_BIT_OR
 *
 * Looks to match the characters the constitute the token OPR_BIT_OR
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mOPR_BIT_OR(pExprCppTreeLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = OPR_BIT_OR;


    // /home/sunowsir/GitHub/2.My_Project/10.Homemade_Programming_Language/5.CC_lib/ExprCppTree.g:158:11: ( '|' )
    // /home/sunowsir/GitHub/2.My_Project/10.Homemade_Programming_Language/5.CC_lib/ExprCppTree.g:158:13: '|'
    {
        MATCHC('|');
        if  (HASEXCEPTION())
        {
            goto ruleOPR_BIT_OREx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleOPR_BIT_OREx; /* Prevent compiler warnings */
    ruleOPR_BIT_OREx: ;

}
// $ANTLR end OPR_BIT_OR

//   Comes from: 159:8: ( '^' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start OPR_XOR
 *
 * Looks to match the characters the constitute the token OPR_XOR
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mOPR_XOR(pExprCppTreeLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = OPR_XOR;


    // /home/sunowsir/GitHub/2.My_Project/10.Homemade_Programming_Language/5.CC_lib/ExprCppTree.g:159:8: ( '^' )
    // /home/sunowsir/GitHub/2.My_Project/10.Homemade_Programming_Language/5.CC_lib/ExprCppTree.g:159:10: '^'
    {
        MATCHC('^');
        if  (HASEXCEPTION())
        {
            goto ruleOPR_XOREx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleOPR_XOREx; /* Prevent compiler warnings */
    ruleOPR_XOREx: ;

}
// $ANTLR end OPR_XOR

//   Comes from: 160:12: ( '&' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start OPR_BIT_AND
 *
 * Looks to match the characters the constitute the token OPR_BIT_AND
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mOPR_BIT_AND(pExprCppTreeLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = OPR_BIT_AND;


    // /home/sunowsir/GitHub/2.My_Project/10.Homemade_Programming_Language/5.CC_lib/ExprCppTree.g:160:12: ( '&' )
    // /home/sunowsir/GitHub/2.My_Project/10.Homemade_Programming_Language/5.CC_lib/ExprCppTree.g:160:14: '&'
    {
        MATCHC('&');
        if  (HASEXCEPTION())
        {
            goto ruleOPR_BIT_ANDEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleOPR_BIT_ANDEx; /* Prevent compiler warnings */
    ruleOPR_BIT_ANDEx: ;

}
// $ANTLR end OPR_BIT_AND

//   Comes from: 161:7: ( '==' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start OPR_EQ
 *
 * Looks to match the characters the constitute the token OPR_EQ
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mOPR_EQ(pExprCppTreeLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = OPR_EQ;


    // /home/sunowsir/GitHub/2.My_Project/10.Homemade_Programming_Language/5.CC_lib/ExprCppTree.g:161:7: ( '==' )
    // /home/sunowsir/GitHub/2.My_Project/10.Homemade_Programming_Language/5.CC_lib/ExprCppTree.g:161:9: '=='
    {
        MATCHS(lit_11);
        if  (HASEXCEPTION())
        {
            goto ruleOPR_EQEx;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleOPR_EQEx; /* Prevent compiler warnings */
    ruleOPR_EQEx: ;

}
// $ANTLR end OPR_EQ

//   Comes from: 162:7: ( '!=' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start OPR_NE
 *
 * Looks to match the characters the constitute the token OPR_NE
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mOPR_NE(pExprCppTreeLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = OPR_NE;


    // /home/sunowsir/GitHub/2.My_Project/10.Homemade_Programming_Language/5.CC_lib/ExprCppTree.g:162:7: ( '!=' )
    // /home/sunowsir/GitHub/2.My_Project/10.Homemade_Programming_Language/5.CC_lib/ExprCppTree.g:162:9: '!='
    {
        MATCHS(lit_12);
        if  (HASEXCEPTION())
        {
            goto ruleOPR_NEEx;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleOPR_NEEx; /* Prevent compiler warnings */
    ruleOPR_NEEx: ;

}
// $ANTLR end OPR_NE

//   Comes from: 163:7: ( '<' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start OPR_LT
 *
 * Looks to match the characters the constitute the token OPR_LT
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mOPR_LT(pExprCppTreeLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = OPR_LT;


    // /home/sunowsir/GitHub/2.My_Project/10.Homemade_Programming_Language/5.CC_lib/ExprCppTree.g:163:7: ( '<' )
    // /home/sunowsir/GitHub/2.My_Project/10.Homemade_Programming_Language/5.CC_lib/ExprCppTree.g:163:9: '<'
    {
        MATCHC('<');
        if  (HASEXCEPTION())
        {
            goto ruleOPR_LTEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleOPR_LTEx; /* Prevent compiler warnings */
    ruleOPR_LTEx: ;

}
// $ANTLR end OPR_LT

//   Comes from: 164:7: ( '<=' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start OPR_LE
 *
 * Looks to match the characters the constitute the token OPR_LE
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mOPR_LE(pExprCppTreeLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = OPR_LE;


    // /home/sunowsir/GitHub/2.My_Project/10.Homemade_Programming_Language/5.CC_lib/ExprCppTree.g:164:7: ( '<=' )
    // /home/sunowsir/GitHub/2.My_Project/10.Homemade_Programming_Language/5.CC_lib/ExprCppTree.g:164:9: '<='
    {
        MATCHS(lit_13);
        if  (HASEXCEPTION())
        {
            goto ruleOPR_LEEx;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleOPR_LEEx; /* Prevent compiler warnings */
    ruleOPR_LEEx: ;

}
// $ANTLR end OPR_LE

//   Comes from: 165:7: ( '>' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start OPR_GT
 *
 * Looks to match the characters the constitute the token OPR_GT
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mOPR_GT(pExprCppTreeLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = OPR_GT;


    // /home/sunowsir/GitHub/2.My_Project/10.Homemade_Programming_Language/5.CC_lib/ExprCppTree.g:165:7: ( '>' )
    // /home/sunowsir/GitHub/2.My_Project/10.Homemade_Programming_Language/5.CC_lib/ExprCppTree.g:165:9: '>'
    {
        MATCHC('>');
        if  (HASEXCEPTION())
        {
            goto ruleOPR_GTEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleOPR_GTEx; /* Prevent compiler warnings */
    ruleOPR_GTEx: ;

}
// $ANTLR end OPR_GT

//   Comes from: 166:7: ( '>=' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start OPR_GE
 *
 * Looks to match the characters the constitute the token OPR_GE
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mOPR_GE(pExprCppTreeLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = OPR_GE;


    // /home/sunowsir/GitHub/2.My_Project/10.Homemade_Programming_Language/5.CC_lib/ExprCppTree.g:166:7: ( '>=' )
    // /home/sunowsir/GitHub/2.My_Project/10.Homemade_Programming_Language/5.CC_lib/ExprCppTree.g:166:9: '>='
    {
        MATCHS(lit_14);
        if  (HASEXCEPTION())
        {
            goto ruleOPR_GEEx;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleOPR_GEEx; /* Prevent compiler warnings */
    ruleOPR_GEEx: ;

}
// $ANTLR end OPR_GE

//   Comes from: 167:9: ( '+' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start OPR_PLUS
 *
 * Looks to match the characters the constitute the token OPR_PLUS
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mOPR_PLUS(pExprCppTreeLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = OPR_PLUS;


    // /home/sunowsir/GitHub/2.My_Project/10.Homemade_Programming_Language/5.CC_lib/ExprCppTree.g:167:9: ( '+' )
    // /home/sunowsir/GitHub/2.My_Project/10.Homemade_Programming_Language/5.CC_lib/ExprCppTree.g:167:11: '+'
    {
        MATCHC('+');
        if  (HASEXCEPTION())
        {
            goto ruleOPR_PLUSEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleOPR_PLUSEx; /* Prevent compiler warnings */
    ruleOPR_PLUSEx: ;

}
// $ANTLR end OPR_PLUS

//   Comes from: 168:10: ( '-' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start OPR_MINUS
 *
 * Looks to match the characters the constitute the token OPR_MINUS
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mOPR_MINUS(pExprCppTreeLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = OPR_MINUS;


    // /home/sunowsir/GitHub/2.My_Project/10.Homemade_Programming_Language/5.CC_lib/ExprCppTree.g:168:10: ( '-' )
    // /home/sunowsir/GitHub/2.My_Project/10.Homemade_Programming_Language/5.CC_lib/ExprCppTree.g:168:12: '-'
    {
        MATCHC('-');
        if  (HASEXCEPTION())
        {
            goto ruleOPR_MINUSEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleOPR_MINUSEx; /* Prevent compiler warnings */
    ruleOPR_MINUSEx: ;

}
// $ANTLR end OPR_MINUS

//   Comes from: 169:9: ( '*' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start OPR_MULT
 *
 * Looks to match the characters the constitute the token OPR_MULT
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mOPR_MULT(pExprCppTreeLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = OPR_MULT;


    // /home/sunowsir/GitHub/2.My_Project/10.Homemade_Programming_Language/5.CC_lib/ExprCppTree.g:169:9: ( '*' )
    // /home/sunowsir/GitHub/2.My_Project/10.Homemade_Programming_Language/5.CC_lib/ExprCppTree.g:169:11: '*'
    {
        MATCHC('*');
        if  (HASEXCEPTION())
        {
            goto ruleOPR_MULTEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleOPR_MULTEx; /* Prevent compiler warnings */
    ruleOPR_MULTEx: ;

}
// $ANTLR end OPR_MULT

//   Comes from: 170:12: ( '/' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start OPR_DIVISOR
 *
 * Looks to match the characters the constitute the token OPR_DIVISOR
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mOPR_DIVISOR(pExprCppTreeLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = OPR_DIVISOR;


    // /home/sunowsir/GitHub/2.My_Project/10.Homemade_Programming_Language/5.CC_lib/ExprCppTree.g:170:12: ( '/' )
    // /home/sunowsir/GitHub/2.My_Project/10.Homemade_Programming_Language/5.CC_lib/ExprCppTree.g:170:14: '/'
    {
        MATCHC('/');
        if  (HASEXCEPTION())
        {
            goto ruleOPR_DIVISOREx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleOPR_DIVISOREx; /* Prevent compiler warnings */
    ruleOPR_DIVISOREx: ;

}
// $ANTLR end OPR_DIVISOR

//   Comes from: 171:12: ( '%' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start OPR_PERCENT
 *
 * Looks to match the characters the constitute the token OPR_PERCENT
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mOPR_PERCENT(pExprCppTreeLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = OPR_PERCENT;


    // /home/sunowsir/GitHub/2.My_Project/10.Homemade_Programming_Language/5.CC_lib/ExprCppTree.g:171:12: ( '%' )
    // /home/sunowsir/GitHub/2.My_Project/10.Homemade_Programming_Language/5.CC_lib/ExprCppTree.g:171:14: '%'
    {
        MATCHC('%');
        if  (HASEXCEPTION())
        {
            goto ruleOPR_PERCENTEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleOPR_PERCENTEx; /* Prevent compiler warnings */
    ruleOPR_PERCENTEx: ;

}
// $ANTLR end OPR_PERCENT

//   Comes from: 172:8: ( '!' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start OPR_NOT
 *
 * Looks to match the characters the constitute the token OPR_NOT
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mOPR_NOT(pExprCppTreeLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = OPR_NOT;


    // /home/sunowsir/GitHub/2.My_Project/10.Homemade_Programming_Language/5.CC_lib/ExprCppTree.g:172:8: ( '!' )
    // /home/sunowsir/GitHub/2.My_Project/10.Homemade_Programming_Language/5.CC_lib/ExprCppTree.g:172:10: '!'
    {
        MATCHC('!');
        if  (HASEXCEPTION())
        {
            goto ruleOPR_NOTEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleOPR_NOTEx; /* Prevent compiler warnings */
    ruleOPR_NOTEx: ;

}
// $ANTLR end OPR_NOT

//   Comes from: 174:17: ( '(' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start PARENTHESES_LEFT
 *
 * Looks to match the characters the constitute the token PARENTHESES_LEFT
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mPARENTHESES_LEFT(pExprCppTreeLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = PARENTHESES_LEFT;


    // /home/sunowsir/GitHub/2.My_Project/10.Homemade_Programming_Language/5.CC_lib/ExprCppTree.g:174:17: ( '(' )
    // /home/sunowsir/GitHub/2.My_Project/10.Homemade_Programming_Language/5.CC_lib/ExprCppTree.g:174:19: '('
    {
        MATCHC('(');
        if  (HASEXCEPTION())
        {
            goto rulePARENTHESES_LEFTEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto rulePARENTHESES_LEFTEx; /* Prevent compiler warnings */
    rulePARENTHESES_LEFTEx: ;

}
// $ANTLR end PARENTHESES_LEFT

//   Comes from: 175:18: ( ')' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start PARENTHESES_RIGHT
 *
 * Looks to match the characters the constitute the token PARENTHESES_RIGHT
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mPARENTHESES_RIGHT(pExprCppTreeLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = PARENTHESES_RIGHT;


    // /home/sunowsir/GitHub/2.My_Project/10.Homemade_Programming_Language/5.CC_lib/ExprCppTree.g:175:18: ( ')' )
    // /home/sunowsir/GitHub/2.My_Project/10.Homemade_Programming_Language/5.CC_lib/ExprCppTree.g:175:20: ')'
    {
        MATCHC(')');
        if  (HASEXCEPTION())
        {
            goto rulePARENTHESES_RIGHTEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto rulePARENTHESES_RIGHTEx; /* Prevent compiler warnings */
    rulePARENTHESES_RIGHTEx: ;

}
// $ANTLR end PARENTHESES_RIGHT

//   Comes from: 176:17: ( '{' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start CURLY_BRACE_LEFT
 *
 * Looks to match the characters the constitute the token CURLY_BRACE_LEFT
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mCURLY_BRACE_LEFT(pExprCppTreeLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = CURLY_BRACE_LEFT;


    // /home/sunowsir/GitHub/2.My_Project/10.Homemade_Programming_Language/5.CC_lib/ExprCppTree.g:176:17: ( '{' )
    // /home/sunowsir/GitHub/2.My_Project/10.Homemade_Programming_Language/5.CC_lib/ExprCppTree.g:176:19: '{'
    {
        MATCHC('{');
        if  (HASEXCEPTION())
        {
            goto ruleCURLY_BRACE_LEFTEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleCURLY_BRACE_LEFTEx; /* Prevent compiler warnings */
    ruleCURLY_BRACE_LEFTEx: ;

}
// $ANTLR end CURLY_BRACE_LEFT

//   Comes from: 177:18: ( '}' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start CURLY_BRACE_RIGHT
 *
 * Looks to match the characters the constitute the token CURLY_BRACE_RIGHT
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mCURLY_BRACE_RIGHT(pExprCppTreeLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = CURLY_BRACE_RIGHT;


    // /home/sunowsir/GitHub/2.My_Project/10.Homemade_Programming_Language/5.CC_lib/ExprCppTree.g:177:18: ( '}' )
    // /home/sunowsir/GitHub/2.My_Project/10.Homemade_Programming_Language/5.CC_lib/ExprCppTree.g:177:20: '}'
    {
        MATCHC('}');
        if  (HASEXCEPTION())
        {
            goto ruleCURLY_BRACE_RIGHTEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleCURLY_BRACE_RIGHTEx; /* Prevent compiler warnings */
    ruleCURLY_BRACE_RIGHTEx: ;

}
// $ANTLR end CURLY_BRACE_RIGHT

//   Comes from: 180:3: ( ( 'a' .. 'z' | 'A' .. 'Z' )+ )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start ID
 *
 * Looks to match the characters the constitute the token ID
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mID(pExprCppTreeLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = ID;


    // /home/sunowsir/GitHub/2.My_Project/10.Homemade_Programming_Language/5.CC_lib/ExprCppTree.g:180:3: ( ( 'a' .. 'z' | 'A' .. 'Z' )+ )
    // /home/sunowsir/GitHub/2.My_Project/10.Homemade_Programming_Language/5.CC_lib/ExprCppTree.g:180:5: ( 'a' .. 'z' | 'A' .. 'Z' )+
    {
        // /home/sunowsir/GitHub/2.My_Project/10.Homemade_Programming_Language/5.CC_lib/ExprCppTree.g:180:5: ( 'a' .. 'z' | 'A' .. 'Z' )+
        {
            int cnt1=0;

            for (;;)
            {
                int alt1=2;
        	switch ( LA(1) )
        	{
        	case 'A':
        	case 'B':
        	case 'C':
        	case 'D':
        	case 'E':
        	case 'F':
        	case 'G':
        	case 'H':
        	case 'I':
        	case 'J':
        	case 'K':
        	case 'L':
        	case 'M':
        	case 'N':
        	case 'O':
        	case 'P':
        	case 'Q':
        	case 'R':
        	case 'S':
        	case 'T':
        	case 'U':
        	case 'V':
        	case 'W':
        	case 'X':
        	case 'Y':
        	case 'Z':
        	case 'a':
        	case 'b':
        	case 'c':
        	case 'd':
        	case 'e':
        	case 'f':
        	case 'g':
        	case 'h':
        	case 'i':
        	case 'j':
        	case 'k':
        	case 'l':
        	case 'm':
        	case 'n':
        	case 'o':
        	case 'p':
        	case 'q':
        	case 'r':
        	case 's':
        	case 't':
        	case 'u':
        	case 'v':
        	case 'w':
        	case 'x':
        	case 'y':
        	case 'z':
        		{
        			alt1=1;
        		}
        	    break;

        	}

        	switch (alt1)
        	{
        	    case 1:
        	        // /home/sunowsir/GitHub/2.My_Project/10.Homemade_Programming_Language/5.CC_lib/ExprCppTree.g:
        	        {
        	            if ( ((LA(1) >= 'A') && (LA(1) <= 'Z')) || ((LA(1) >= 'a') && (LA(1) <= 'z')) )
        	            {
        	                CONSUME();
        	            }
        	            else
        	            {
        	                CONSTRUCTEX();
        	                EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
        	                EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

        	                LRECOVER();
        	                goto ruleIDEx;
        	            }


        	        }
        	        break;

        	    default:

        		if ( cnt1 >= 1 )
        		{
        		    goto loop1;
        		}
        		/* mismatchedSetEx()
        		 */
        		CONSTRUCTEX();
        		EXCEPTION->type = ANTLR3_EARLY_EXIT_EXCEPTION;
        		EXCEPTION->name = (void *)ANTLR3_EARLY_EXIT_NAME;


        		goto ruleIDEx;
        	}
        	cnt1++;
            }
            loop1: ;	/* Jump to here if this rule does not match */
        }

    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleIDEx; /* Prevent compiler warnings */
    ruleIDEx: ;

}
// $ANTLR end ID

//   Comes from: 181:4: ( ( '~' )? ( '0' .. '9' )+ )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start INT
 *
 * Looks to match the characters the constitute the token INT
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mINT(pExprCppTreeLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = INT;


    // /home/sunowsir/GitHub/2.My_Project/10.Homemade_Programming_Language/5.CC_lib/ExprCppTree.g:181:4: ( ( '~' )? ( '0' .. '9' )+ )
    // /home/sunowsir/GitHub/2.My_Project/10.Homemade_Programming_Language/5.CC_lib/ExprCppTree.g:181:6: ( '~' )? ( '0' .. '9' )+
    {
        // /home/sunowsir/GitHub/2.My_Project/10.Homemade_Programming_Language/5.CC_lib/ExprCppTree.g:181:6: ( '~' )?
        {
            int alt2=2;
            switch ( LA(1) )
            {
                case '~':
                	{
                		alt2=1;
                	}
                    break;
            }

            switch (alt2)
            {
        	case 1:
        	    // /home/sunowsir/GitHub/2.My_Project/10.Homemade_Programming_Language/5.CC_lib/ExprCppTree.g:181:6: '~'
        	    {
        	        MATCHC('~');
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleINTEx;
        	        }


        	    }
        	    break;

            }
        }

        // /home/sunowsir/GitHub/2.My_Project/10.Homemade_Programming_Language/5.CC_lib/ExprCppTree.g:181:11: ( '0' .. '9' )+
        {
            int cnt3=0;

            for (;;)
            {
                int alt3=2;
        	switch ( LA(1) )
        	{
        	case '0':
        	case '1':
        	case '2':
        	case '3':
        	case '4':
        	case '5':
        	case '6':
        	case '7':
        	case '8':
        	case '9':
        		{
        			alt3=1;
        		}
        	    break;

        	}

        	switch (alt3)
        	{
        	    case 1:
        	        // /home/sunowsir/GitHub/2.My_Project/10.Homemade_Programming_Language/5.CC_lib/ExprCppTree.g:
        	        {
        	            if ( ((LA(1) >= '0') && (LA(1) <= '9')) )
        	            {
        	                CONSUME();
        	            }
        	            else
        	            {
        	                CONSTRUCTEX();
        	                EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
        	                EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

        	                LRECOVER();
        	                goto ruleINTEx;
        	            }


        	        }
        	        break;

        	    default:

        		if ( cnt3 >= 1 )
        		{
        		    goto loop3;
        		}
        		/* mismatchedSetEx()
        		 */
        		CONSTRUCTEX();
        		EXCEPTION->type = ANTLR3_EARLY_EXIT_EXCEPTION;
        		EXCEPTION->name = (void *)ANTLR3_EARLY_EXIT_NAME;


        		goto ruleINTEx;
        	}
        	cnt3++;
            }
            loop3: ;	/* Jump to here if this rule does not match */
        }

    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleINTEx; /* Prevent compiler warnings */
    ruleINTEx: ;

}
// $ANTLR end INT

//   Comes from: 183:8: ( ( '\\r' )? ( '\\n' )* )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start ENDLINE
 *
 * Looks to match the characters the constitute the token ENDLINE
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mENDLINE(pExprCppTreeLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = ENDLINE;


    // /home/sunowsir/GitHub/2.My_Project/10.Homemade_Programming_Language/5.CC_lib/ExprCppTree.g:183:8: ( ( '\\r' )? ( '\\n' )* )
    // /home/sunowsir/GitHub/2.My_Project/10.Homemade_Programming_Language/5.CC_lib/ExprCppTree.g:183:10: ( '\\r' )? ( '\\n' )*
    {
        // /home/sunowsir/GitHub/2.My_Project/10.Homemade_Programming_Language/5.CC_lib/ExprCppTree.g:183:10: ( '\\r' )?
        {
            int alt4=2;
            switch ( LA(1) )
            {
                case '\r':
                	{
                		alt4=1;
                	}
                    break;
            }

            switch (alt4)
            {
        	case 1:
        	    // /home/sunowsir/GitHub/2.My_Project/10.Homemade_Programming_Language/5.CC_lib/ExprCppTree.g:183:10: '\\r'
        	    {
        	        MATCHC('\r');
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleENDLINEEx;
        	        }


        	    }
        	    break;

            }
        }

        // /home/sunowsir/GitHub/2.My_Project/10.Homemade_Programming_Language/5.CC_lib/ExprCppTree.g:183:16: ( '\\n' )*

        for (;;)
        {
            int alt5=2;
            switch ( LA(1) )
            {
            case '\n':
            	{
            		alt5=1;
            	}
                break;

            }

            switch (alt5)
            {
        	case 1:
        	    // /home/sunowsir/GitHub/2.My_Project/10.Homemade_Programming_Language/5.CC_lib/ExprCppTree.g:183:16: '\\n'
        	    {
        	        MATCHC('\n');
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleENDLINEEx;
        	        }


        	    }
        	    break;

        	default:
        	    goto loop5;	/* break out of the loop */
        	    break;
            }
        }
        loop5: ; /* Jump out to here if this rule does not match */


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleENDLINEEx; /* Prevent compiler warnings */
    ruleENDLINEEx: ;

}
// $ANTLR end ENDLINE

//   Comes from: 185:4: ( ( ' ' | '\\t' )+ )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start WS
 *
 * Looks to match the characters the constitute the token WS
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mWS(pExprCppTreeLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = WS;


    // /home/sunowsir/GitHub/2.My_Project/10.Homemade_Programming_Language/5.CC_lib/ExprCppTree.g:185:4: ( ( ' ' | '\\t' )+ )
    // /home/sunowsir/GitHub/2.My_Project/10.Homemade_Programming_Language/5.CC_lib/ExprCppTree.g:185:6: ( ' ' | '\\t' )+
    {
        // /home/sunowsir/GitHub/2.My_Project/10.Homemade_Programming_Language/5.CC_lib/ExprCppTree.g:185:6: ( ' ' | '\\t' )+
        {
            int cnt6=0;

            for (;;)
            {
                int alt6=2;
        	switch ( LA(1) )
        	{
        	case '\t':
        	case ' ':
        		{
        			alt6=1;
        		}
        	    break;

        	}

        	switch (alt6)
        	{
        	    case 1:
        	        // /home/sunowsir/GitHub/2.My_Project/10.Homemade_Programming_Language/5.CC_lib/ExprCppTree.g:
        	        {
        	            if ( LA(1) == '\t' || LA(1) == ' ' )
        	            {
        	                CONSUME();
        	            }
        	            else
        	            {
        	                CONSTRUCTEX();
        	                EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
        	                EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

        	                LRECOVER();
        	                goto ruleWSEx;
        	            }


        	        }
        	        break;

        	    default:

        		if ( cnt6 >= 1 )
        		{
        		    goto loop6;
        		}
        		/* mismatchedSetEx()
        		 */
        		CONSTRUCTEX();
        		EXCEPTION->type = ANTLR3_EARLY_EXIT_EXCEPTION;
        		EXCEPTION->name = (void *)ANTLR3_EARLY_EXIT_NAME;


        		goto ruleWSEx;
        	}
        	cnt6++;
            }
            loop6: ;	/* Jump to here if this rule does not match */
        }

        {
            LEXSTATE->channel = HIDDEN;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleWSEx; /* Prevent compiler warnings */
    ruleWSEx: ;

}
// $ANTLR end WS

/** This is the entry point in to the lexer from an object that
 *  wants to generate the next token, such as a pCOMMON_TOKEN_STREAM
 */
static void
mTokens(pExprCppTreeLexer ctx)
{
    {
        //  /home/sunowsir/GitHub/2.My_Project/10.Homemade_Programming_Language/5.CC_lib/ExprCppTree.g:1:8: ( T__40 | KW_MAIN | KW_IF | KW_ELIF | KW_ELSE | KW_FOR | KW_WHILE | KW_DO | KW_DEF | OPR_COMMA | OPR_ASSIGN | OPR_OR | OPR_AND | OPR_BIT_OR | OPR_XOR | OPR_BIT_AND | OPR_EQ | OPR_NE | OPR_LT | OPR_LE | OPR_GT | OPR_GE | OPR_PLUS | OPR_MINUS | OPR_MULT | OPR_DIVISOR | OPR_PERCENT | OPR_NOT | PARENTHESES_LEFT | PARENTHESES_RIGHT | CURLY_BRACE_LEFT | CURLY_BRACE_RIGHT | ID | INT | ENDLINE | WS )

        ANTLR3_UINT32 alt7;

        alt7=36;

        switch ( LA(1) )
        {
        case ';':
        	{
        		alt7=1;
        	}
            break;
        case 'm':
        	{
        		switch ( LA(2) )
        		{
        		case 'a':
        			{
        				switch ( LA(3) )
        				{
        				case 'i':
        					{
        						switch ( LA(4) )
        						{
        						case 'n':
        							{
        								switch ( LA(5) )
        								{
        								case 'A':
        								case 'B':
        								case 'C':
        								case 'D':
        								case 'E':
        								case 'F':
        								case 'G':
        								case 'H':
        								case 'I':
        								case 'J':
        								case 'K':
        								case 'L':
        								case 'M':
        								case 'N':
        								case 'O':
        								case 'P':
        								case 'Q':
        								case 'R':
        								case 'S':
        								case 'T':
        								case 'U':
        								case 'V':
        								case 'W':
        								case 'X':
        								case 'Y':
        								case 'Z':
        								case 'a':
        								case 'b':
        								case 'c':
        								case 'd':
        								case 'e':
        								case 'f':
        								case 'g':
        								case 'h':
        								case 'i':
        								case 'j':
        								case 'k':
        								case 'l':
        								case 'm':
        								case 'n':
        								case 'o':
        								case 'p':
        								case 'q':
        								case 'r':
        								case 's':
        								case 't':
        								case 'u':
        								case 'v':
        								case 'w':
        								case 'x':
        								case 'y':
        								case 'z':
        									{
        										alt7=33;
        									}
        								    break;

        								default:
        								    alt7=2;
        								}

        							}
        						    break;

        						default:
        						    alt7=33;
        						}

        					}
        				    break;

        				default:
        				    alt7=33;
        				}

        			}
        		    break;

        		default:
        		    alt7=33;
        		}

        	}
            break;
        case 'i':
        	{
        		switch ( LA(2) )
        		{
        		case 'f':
        			{
        				switch ( LA(3) )
        				{
        				case 'A':
        				case 'B':
        				case 'C':
        				case 'D':
        				case 'E':
        				case 'F':
        				case 'G':
        				case 'H':
        				case 'I':
        				case 'J':
        				case 'K':
        				case 'L':
        				case 'M':
        				case 'N':
        				case 'O':
        				case 'P':
        				case 'Q':
        				case 'R':
        				case 'S':
        				case 'T':
        				case 'U':
        				case 'V':
        				case 'W':
        				case 'X':
        				case 'Y':
        				case 'Z':
        				case 'a':
        				case 'b':
        				case 'c':
        				case 'd':
        				case 'e':
        				case 'f':
        				case 'g':
        				case 'h':
        				case 'i':
        				case 'j':
        				case 'k':
        				case 'l':
        				case 'm':
        				case 'n':
        				case 'o':
        				case 'p':
        				case 'q':
        				case 'r':
        				case 's':
        				case 't':
        				case 'u':
        				case 'v':
        				case 'w':
        				case 'x':
        				case 'y':
        				case 'z':
        					{
        						alt7=33;
        					}
        				    break;

        				default:
        				    alt7=3;
        				}

        			}
        		    break;

        		default:
        		    alt7=33;
        		}

        	}
            break;
        case 'e':
        	{
        		switch ( LA(2) )
        		{
        		case 'l':
        			{
        				switch ( LA(3) )
        				{
        				case 'i':
        					{
        						switch ( LA(4) )
        						{
        						case 'f':
        							{
        								switch ( LA(5) )
        								{
        								case 'A':
        								case 'B':
        								case 'C':
        								case 'D':
        								case 'E':
        								case 'F':
        								case 'G':
        								case 'H':
        								case 'I':
        								case 'J':
        								case 'K':
        								case 'L':
        								case 'M':
        								case 'N':
        								case 'O':
        								case 'P':
        								case 'Q':
        								case 'R':
        								case 'S':
        								case 'T':
        								case 'U':
        								case 'V':
        								case 'W':
        								case 'X':
        								case 'Y':
        								case 'Z':
        								case 'a':
        								case 'b':
        								case 'c':
        								case 'd':
        								case 'e':
        								case 'f':
        								case 'g':
        								case 'h':
        								case 'i':
        								case 'j':
        								case 'k':
        								case 'l':
        								case 'm':
        								case 'n':
        								case 'o':
        								case 'p':
        								case 'q':
        								case 'r':
        								case 's':
        								case 't':
        								case 'u':
        								case 'v':
        								case 'w':
        								case 'x':
        								case 'y':
        								case 'z':
        									{
        										alt7=33;
        									}
        								    break;

        								default:
        								    alt7=4;
        								}

        							}
        						    break;

        						default:
        						    alt7=33;
        						}

        					}
        				    break;
        				case 's':
        					{
        						switch ( LA(4) )
        						{
        						case 'e':
        							{
        								switch ( LA(5) )
        								{
        								case 'A':
        								case 'B':
        								case 'C':
        								case 'D':
        								case 'E':
        								case 'F':
        								case 'G':
        								case 'H':
        								case 'I':
        								case 'J':
        								case 'K':
        								case 'L':
        								case 'M':
        								case 'N':
        								case 'O':
        								case 'P':
        								case 'Q':
        								case 'R':
        								case 'S':
        								case 'T':
        								case 'U':
        								case 'V':
        								case 'W':
        								case 'X':
        								case 'Y':
        								case 'Z':
        								case 'a':
        								case 'b':
        								case 'c':
        								case 'd':
        								case 'e':
        								case 'f':
        								case 'g':
        								case 'h':
        								case 'i':
        								case 'j':
        								case 'k':
        								case 'l':
        								case 'm':
        								case 'n':
        								case 'o':
        								case 'p':
        								case 'q':
        								case 'r':
        								case 's':
        								case 't':
        								case 'u':
        								case 'v':
        								case 'w':
        								case 'x':
        								case 'y':
        								case 'z':
        									{
        										alt7=33;
        									}
        								    break;

        								default:
        								    alt7=5;
        								}

        							}
        						    break;

        						default:
        						    alt7=33;
        						}

        					}
        				    break;

        				default:
        				    alt7=33;
        				}

        			}
        		    break;

        		default:
        		    alt7=33;
        		}

        	}
            break;
        case 'f':
        	{
        		switch ( LA(2) )
        		{
        		case 'o':
        			{
        				switch ( LA(3) )
        				{
        				case 'r':
        					{
        						switch ( LA(4) )
        						{
        						case 'A':
        						case 'B':
        						case 'C':
        						case 'D':
        						case 'E':
        						case 'F':
        						case 'G':
        						case 'H':
        						case 'I':
        						case 'J':
        						case 'K':
        						case 'L':
        						case 'M':
        						case 'N':
        						case 'O':
        						case 'P':
        						case 'Q':
        						case 'R':
        						case 'S':
        						case 'T':
        						case 'U':
        						case 'V':
        						case 'W':
        						case 'X':
        						case 'Y':
        						case 'Z':
        						case 'a':
        						case 'b':
        						case 'c':
        						case 'd':
        						case 'e':
        						case 'f':
        						case 'g':
        						case 'h':
        						case 'i':
        						case 'j':
        						case 'k':
        						case 'l':
        						case 'm':
        						case 'n':
        						case 'o':
        						case 'p':
        						case 'q':
        						case 'r':
        						case 's':
        						case 't':
        						case 'u':
        						case 'v':
        						case 'w':
        						case 'x':
        						case 'y':
        						case 'z':
        							{
        								alt7=33;
        							}
        						    break;

        						default:
        						    alt7=6;
        						}

        					}
        				    break;

        				default:
        				    alt7=33;
        				}

        			}
        		    break;

        		default:
        		    alt7=33;
        		}

        	}
            break;
        case 'w':
        	{
        		switch ( LA(2) )
        		{
        		case 'h':
        			{
        				switch ( LA(3) )
        				{
        				case 'i':
        					{
        						switch ( LA(4) )
        						{
        						case 'l':
        							{
        								switch ( LA(5) )
        								{
        								case 'e':
        									{
        										switch ( LA(6) )
        										{
        										case 'A':
        										case 'B':
        										case 'C':
        										case 'D':
        										case 'E':
        										case 'F':
        										case 'G':
        										case 'H':
        										case 'I':
        										case 'J':
        										case 'K':
        										case 'L':
        										case 'M':
        										case 'N':
        										case 'O':
        										case 'P':
        										case 'Q':
        										case 'R':
        										case 'S':
        										case 'T':
        										case 'U':
        										case 'V':
        										case 'W':
        										case 'X':
        										case 'Y':
        										case 'Z':
        										case 'a':
        										case 'b':
        										case 'c':
        										case 'd':
        										case 'e':
        										case 'f':
        										case 'g':
        										case 'h':
        										case 'i':
        										case 'j':
        										case 'k':
        										case 'l':
        										case 'm':
        										case 'n':
        										case 'o':
        										case 'p':
        										case 'q':
        										case 'r':
        										case 's':
        										case 't':
        										case 'u':
        										case 'v':
        										case 'w':
        										case 'x':
        										case 'y':
        										case 'z':
        											{
        												alt7=33;
        											}
        										    break;

        										default:
        										    alt7=7;
        										}

        									}
        								    break;

        								default:
        								    alt7=33;
        								}

        							}
        						    break;

        						default:
        						    alt7=33;
        						}

        					}
        				    break;

        				default:
        				    alt7=33;
        				}

        			}
        		    break;

        		default:
        		    alt7=33;
        		}

        	}
            break;
        case 'd':
        	{
        		switch ( LA(2) )
        		{
        		case 'o':
        			{
        				switch ( LA(3) )
        				{
        				case 'A':
        				case 'B':
        				case 'C':
        				case 'D':
        				case 'E':
        				case 'F':
        				case 'G':
        				case 'H':
        				case 'I':
        				case 'J':
        				case 'K':
        				case 'L':
        				case 'M':
        				case 'N':
        				case 'O':
        				case 'P':
        				case 'Q':
        				case 'R':
        				case 'S':
        				case 'T':
        				case 'U':
        				case 'V':
        				case 'W':
        				case 'X':
        				case 'Y':
        				case 'Z':
        				case 'a':
        				case 'b':
        				case 'c':
        				case 'd':
        				case 'e':
        				case 'f':
        				case 'g':
        				case 'h':
        				case 'i':
        				case 'j':
        				case 'k':
        				case 'l':
        				case 'm':
        				case 'n':
        				case 'o':
        				case 'p':
        				case 'q':
        				case 'r':
        				case 's':
        				case 't':
        				case 'u':
        				case 'v':
        				case 'w':
        				case 'x':
        				case 'y':
        				case 'z':
        					{
        						alt7=33;
        					}
        				    break;

        				default:
        				    alt7=8;
        				}

        			}
        		    break;
        		case 'e':
        			{
        				switch ( LA(3) )
        				{
        				case 'f':
        					{
        						switch ( LA(4) )
        						{
        						case 'A':
        						case 'B':
        						case 'C':
        						case 'D':
        						case 'E':
        						case 'F':
        						case 'G':
        						case 'H':
        						case 'I':
        						case 'J':
        						case 'K':
        						case 'L':
        						case 'M':
        						case 'N':
        						case 'O':
        						case 'P':
        						case 'Q':
        						case 'R':
        						case 'S':
        						case 'T':
        						case 'U':
        						case 'V':
        						case 'W':
        						case 'X':
        						case 'Y':
        						case 'Z':
        						case 'a':
        						case 'b':
        						case 'c':
        						case 'd':
        						case 'e':
        						case 'f':
        						case 'g':
        						case 'h':
        						case 'i':
        						case 'j':
        						case 'k':
        						case 'l':
        						case 'm':
        						case 'n':
        						case 'o':
        						case 'p':
        						case 'q':
        						case 'r':
        						case 's':
        						case 't':
        						case 'u':
        						case 'v':
        						case 'w':
        						case 'x':
        						case 'y':
        						case 'z':
        							{
        								alt7=33;
        							}
        						    break;

        						default:
        						    alt7=9;
        						}

        					}
        				    break;

        				default:
        				    alt7=33;
        				}

        			}
        		    break;

        		default:
        		    alt7=33;
        		}

        	}
            break;
        case ',':
        	{
        		alt7=10;
        	}
            break;
        case '=':
        	{
        		switch ( LA(2) )
        		{
        		case '=':
        			{
        				alt7=17;
        			}
        		    break;

        		default:
        		    alt7=11;
        		}

        	}
            break;
        case '|':
        	{
        		switch ( LA(2) )
        		{
        		case '|':
        			{
        				alt7=12;
        			}
        		    break;

        		default:
        		    alt7=14;
        		}

        	}
            break;
        case '&':
        	{
        		switch ( LA(2) )
        		{
        		case '&':
        			{
        				alt7=13;
        			}
        		    break;

        		default:
        		    alt7=16;
        		}

        	}
            break;
        case '^':
        	{
        		alt7=15;
        	}
            break;
        case '!':
        	{
        		switch ( LA(2) )
        		{
        		case '=':
        			{
        				alt7=18;
        			}
        		    break;

        		default:
        		    alt7=28;
        		}

        	}
            break;
        case '<':
        	{
        		switch ( LA(2) )
        		{
        		case '=':
        			{
        				alt7=20;
        			}
        		    break;

        		default:
        		    alt7=19;
        		}

        	}
            break;
        case '>':
        	{
        		switch ( LA(2) )
        		{
        		case '=':
        			{
        				alt7=22;
        			}
        		    break;

        		default:
        		    alt7=21;
        		}

        	}
            break;
        case '+':
        	{
        		alt7=23;
        	}
            break;
        case '-':
        	{
        		alt7=24;
        	}
            break;
        case '*':
        	{
        		alt7=25;
        	}
            break;
        case '/':
        	{
        		alt7=26;
        	}
            break;
        case '%':
        	{
        		alt7=27;
        	}
            break;
        case '(':
        	{
        		alt7=29;
        	}
            break;
        case ')':
        	{
        		alt7=30;
        	}
            break;
        case '{':
        	{
        		alt7=31;
        	}
            break;
        case '}':
        	{
        		alt7=32;
        	}
            break;
        case 'A':
        case 'B':
        case 'C':
        case 'D':
        case 'E':
        case 'F':
        case 'G':
        case 'H':
        case 'I':
        case 'J':
        case 'K':
        case 'L':
        case 'M':
        case 'N':
        case 'O':
        case 'P':
        case 'Q':
        case 'R':
        case 'S':
        case 'T':
        case 'U':
        case 'V':
        case 'W':
        case 'X':
        case 'Y':
        case 'Z':
        case 'a':
        case 'b':
        case 'c':
        case 'g':
        case 'h':
        case 'j':
        case 'k':
        case 'l':
        case 'n':
        case 'o':
        case 'p':
        case 'q':
        case 'r':
        case 's':
        case 't':
        case 'u':
        case 'v':
        case 'x':
        case 'y':
        case 'z':
        	{
        		alt7=33;
        	}
            break;
        case '0':
        case '1':
        case '2':
        case '3':
        case '4':
        case '5':
        case '6':
        case '7':
        case '8':
        case '9':
        case '~':
        	{
        		alt7=34;
        	}
            break;
        case '\t':
        case ' ':
        	{
        		alt7=36;
        	}
            break;

        default:
            alt7=35;
        }

        switch (alt7)
        {
    	case 1:
    	    // /home/sunowsir/GitHub/2.My_Project/10.Homemade_Programming_Language/5.CC_lib/ExprCppTree.g:1:10: T__40
    	    {
    	        /* 1:10: T__40 */
    	        mT__40(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 2:
    	    // /home/sunowsir/GitHub/2.My_Project/10.Homemade_Programming_Language/5.CC_lib/ExprCppTree.g:1:16: KW_MAIN
    	    {
    	        /* 1:16: KW_MAIN */
    	        mKW_MAIN(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 3:
    	    // /home/sunowsir/GitHub/2.My_Project/10.Homemade_Programming_Language/5.CC_lib/ExprCppTree.g:1:24: KW_IF
    	    {
    	        /* 1:24: KW_IF */
    	        mKW_IF(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 4:
    	    // /home/sunowsir/GitHub/2.My_Project/10.Homemade_Programming_Language/5.CC_lib/ExprCppTree.g:1:30: KW_ELIF
    	    {
    	        /* 1:30: KW_ELIF */
    	        mKW_ELIF(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 5:
    	    // /home/sunowsir/GitHub/2.My_Project/10.Homemade_Programming_Language/5.CC_lib/ExprCppTree.g:1:38: KW_ELSE
    	    {
    	        /* 1:38: KW_ELSE */
    	        mKW_ELSE(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 6:
    	    // /home/sunowsir/GitHub/2.My_Project/10.Homemade_Programming_Language/5.CC_lib/ExprCppTree.g:1:46: KW_FOR
    	    {
    	        /* 1:46: KW_FOR */
    	        mKW_FOR(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 7:
    	    // /home/sunowsir/GitHub/2.My_Project/10.Homemade_Programming_Language/5.CC_lib/ExprCppTree.g:1:53: KW_WHILE
    	    {
    	        /* 1:53: KW_WHILE */
    	        mKW_WHILE(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 8:
    	    // /home/sunowsir/GitHub/2.My_Project/10.Homemade_Programming_Language/5.CC_lib/ExprCppTree.g:1:62: KW_DO
    	    {
    	        /* 1:62: KW_DO */
    	        mKW_DO(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 9:
    	    // /home/sunowsir/GitHub/2.My_Project/10.Homemade_Programming_Language/5.CC_lib/ExprCppTree.g:1:68: KW_DEF
    	    {
    	        /* 1:68: KW_DEF */
    	        mKW_DEF(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 10:
    	    // /home/sunowsir/GitHub/2.My_Project/10.Homemade_Programming_Language/5.CC_lib/ExprCppTree.g:1:75: OPR_COMMA
    	    {
    	        /* 1:75: OPR_COMMA */
    	        mOPR_COMMA(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 11:
    	    // /home/sunowsir/GitHub/2.My_Project/10.Homemade_Programming_Language/5.CC_lib/ExprCppTree.g:1:85: OPR_ASSIGN
    	    {
    	        /* 1:85: OPR_ASSIGN */
    	        mOPR_ASSIGN(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 12:
    	    // /home/sunowsir/GitHub/2.My_Project/10.Homemade_Programming_Language/5.CC_lib/ExprCppTree.g:1:96: OPR_OR
    	    {
    	        /* 1:96: OPR_OR */
    	        mOPR_OR(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 13:
    	    // /home/sunowsir/GitHub/2.My_Project/10.Homemade_Programming_Language/5.CC_lib/ExprCppTree.g:1:103: OPR_AND
    	    {
    	        /* 1:103: OPR_AND */
    	        mOPR_AND(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 14:
    	    // /home/sunowsir/GitHub/2.My_Project/10.Homemade_Programming_Language/5.CC_lib/ExprCppTree.g:1:111: OPR_BIT_OR
    	    {
    	        /* 1:111: OPR_BIT_OR */
    	        mOPR_BIT_OR(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 15:
    	    // /home/sunowsir/GitHub/2.My_Project/10.Homemade_Programming_Language/5.CC_lib/ExprCppTree.g:1:122: OPR_XOR
    	    {
    	        /* 1:122: OPR_XOR */
    	        mOPR_XOR(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 16:
    	    // /home/sunowsir/GitHub/2.My_Project/10.Homemade_Programming_Language/5.CC_lib/ExprCppTree.g:1:130: OPR_BIT_AND
    	    {
    	        /* 1:130: OPR_BIT_AND */
    	        mOPR_BIT_AND(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 17:
    	    // /home/sunowsir/GitHub/2.My_Project/10.Homemade_Programming_Language/5.CC_lib/ExprCppTree.g:1:142: OPR_EQ
    	    {
    	        /* 1:142: OPR_EQ */
    	        mOPR_EQ(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 18:
    	    // /home/sunowsir/GitHub/2.My_Project/10.Homemade_Programming_Language/5.CC_lib/ExprCppTree.g:1:149: OPR_NE
    	    {
    	        /* 1:149: OPR_NE */
    	        mOPR_NE(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 19:
    	    // /home/sunowsir/GitHub/2.My_Project/10.Homemade_Programming_Language/5.CC_lib/ExprCppTree.g:1:156: OPR_LT
    	    {
    	        /* 1:156: OPR_LT */
    	        mOPR_LT(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 20:
    	    // /home/sunowsir/GitHub/2.My_Project/10.Homemade_Programming_Language/5.CC_lib/ExprCppTree.g:1:163: OPR_LE
    	    {
    	        /* 1:163: OPR_LE */
    	        mOPR_LE(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 21:
    	    // /home/sunowsir/GitHub/2.My_Project/10.Homemade_Programming_Language/5.CC_lib/ExprCppTree.g:1:170: OPR_GT
    	    {
    	        /* 1:170: OPR_GT */
    	        mOPR_GT(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 22:
    	    // /home/sunowsir/GitHub/2.My_Project/10.Homemade_Programming_Language/5.CC_lib/ExprCppTree.g:1:177: OPR_GE
    	    {
    	        /* 1:177: OPR_GE */
    	        mOPR_GE(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 23:
    	    // /home/sunowsir/GitHub/2.My_Project/10.Homemade_Programming_Language/5.CC_lib/ExprCppTree.g:1:184: OPR_PLUS
    	    {
    	        /* 1:184: OPR_PLUS */
    	        mOPR_PLUS(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 24:
    	    // /home/sunowsir/GitHub/2.My_Project/10.Homemade_Programming_Language/5.CC_lib/ExprCppTree.g:1:193: OPR_MINUS
    	    {
    	        /* 1:193: OPR_MINUS */
    	        mOPR_MINUS(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 25:
    	    // /home/sunowsir/GitHub/2.My_Project/10.Homemade_Programming_Language/5.CC_lib/ExprCppTree.g:1:203: OPR_MULT
    	    {
    	        /* 1:203: OPR_MULT */
    	        mOPR_MULT(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 26:
    	    // /home/sunowsir/GitHub/2.My_Project/10.Homemade_Programming_Language/5.CC_lib/ExprCppTree.g:1:212: OPR_DIVISOR
    	    {
    	        /* 1:212: OPR_DIVISOR */
    	        mOPR_DIVISOR(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 27:
    	    // /home/sunowsir/GitHub/2.My_Project/10.Homemade_Programming_Language/5.CC_lib/ExprCppTree.g:1:224: OPR_PERCENT
    	    {
    	        /* 1:224: OPR_PERCENT */
    	        mOPR_PERCENT(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 28:
    	    // /home/sunowsir/GitHub/2.My_Project/10.Homemade_Programming_Language/5.CC_lib/ExprCppTree.g:1:236: OPR_NOT
    	    {
    	        /* 1:236: OPR_NOT */
    	        mOPR_NOT(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 29:
    	    // /home/sunowsir/GitHub/2.My_Project/10.Homemade_Programming_Language/5.CC_lib/ExprCppTree.g:1:244: PARENTHESES_LEFT
    	    {
    	        /* 1:244: PARENTHESES_LEFT */
    	        mPARENTHESES_LEFT(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 30:
    	    // /home/sunowsir/GitHub/2.My_Project/10.Homemade_Programming_Language/5.CC_lib/ExprCppTree.g:1:261: PARENTHESES_RIGHT
    	    {
    	        /* 1:261: PARENTHESES_RIGHT */
    	        mPARENTHESES_RIGHT(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 31:
    	    // /home/sunowsir/GitHub/2.My_Project/10.Homemade_Programming_Language/5.CC_lib/ExprCppTree.g:1:279: CURLY_BRACE_LEFT
    	    {
    	        /* 1:279: CURLY_BRACE_LEFT */
    	        mCURLY_BRACE_LEFT(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 32:
    	    // /home/sunowsir/GitHub/2.My_Project/10.Homemade_Programming_Language/5.CC_lib/ExprCppTree.g:1:296: CURLY_BRACE_RIGHT
    	    {
    	        /* 1:296: CURLY_BRACE_RIGHT */
    	        mCURLY_BRACE_RIGHT(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 33:
    	    // /home/sunowsir/GitHub/2.My_Project/10.Homemade_Programming_Language/5.CC_lib/ExprCppTree.g:1:314: ID
    	    {
    	        /* 1:314: ID */
    	        mID(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 34:
    	    // /home/sunowsir/GitHub/2.My_Project/10.Homemade_Programming_Language/5.CC_lib/ExprCppTree.g:1:317: INT
    	    {
    	        /* 1:317: INT */
    	        mINT(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 35:
    	    // /home/sunowsir/GitHub/2.My_Project/10.Homemade_Programming_Language/5.CC_lib/ExprCppTree.g:1:321: ENDLINE
    	    {
    	        /* 1:321: ENDLINE */
    	        mENDLINE(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 36:
    	    // /home/sunowsir/GitHub/2.My_Project/10.Homemade_Programming_Language/5.CC_lib/ExprCppTree.g:1:329: WS
    	    {
    	        /* 1:329: WS */
    	        mWS(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;

        }
    }


    goto ruleTokensEx; /* Prevent compiler warnings */
ruleTokensEx: ;
}

/* =========================================================================
 * Lexer matching rules end.
 * =========================================================================
 */
/* End of Lexer code
 * ================================================
 * ================================================
 */


/* End of code
 * =============================================================================
 */
